[tool.poetry]
name = "exasol-script-languages-release"
version = "8.3.0"
description = "Script Languages Release"

license = "MIT"

authors = [
    "Torsten Kilias <torsten.kilias@exasol.com>",
    "Thomas Uebensee <ext.thomas.uebensee@exasol.com>"
]

readme = 'README.md'  # Markdown files are supported

repository = "https://github.com/exasol/script-languages-release"
homepage = "https://github.com/exasol/script-languages-release"

keywords = ['exasol', 'udf', 'script-languages']

[tool.poetry.dependencies]
python = ">=3.10,<4"
exasol-script-languages-container-tool = "^0.20.0"
exasol-script-languages-container-ci = "^1.5.0"
exasol-script-languages-container-ci-setup = "^1.4.0"
pandas = "^2.2.2"
tabulate = "^0.9.0"
click = "^8.1.7"
docker = "!= 7.0.0"

[tool.poetry.dev-dependencies]
toml = ">=0.10.2"
gitpython = ">=3.1.0"

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
