CREATE SCHEMA IF NOT EXISTS TEST;
OPEN SCHEMA TEST;
--/

CREATE OR REPLACE PYTHON SET SCRIPT "TEST_PYTHON_VERSION" ("i" DECIMAL(18,0)) EMITS ("O" VARCHAR(2000000) UTF8) AS
import sys
def run(ctx):
    ctx.emit(sys.version)
/

