tele:
  sync:
    - --include=build/
    - --include=.bcc/
    - --include=.bcc/build 
    - --include=.bcc/build/*
    - --include=.bcc/build/*/.bcc
  dont_sync:
    - --exclude=.build/ 
    - --exclude=.build.ccc 
    - --exclude=.ccc[.-]*
    - --exclude=.bcc.env 
    - --exclude=.env.dump 
    - --exclude=.ninja_deps
    - --exclude=.ninja_log 
    - --exclude=.sconsign.dblite 
    - --exclude=.sconf_temp
    - --exclude=JDBC/bin/com/exasol/jdbc/version.res 
    - --exclude=.git/
    - --exclude=TAGS
    - --exclude=*~
    - --exclude=*.old
    - --exclude=*.bak
    - --exclude=*.orig
    - --exclude=*.swp
