#!/usr/bin/env bash
set -ue


## CMD Functions: Help
_cmd_help()
{
  cat <<EOF
Usage:

    c4 make [CMD]

Defined build and install interface of C4 for generic integration of the nvidia driver libraries into c4.

Commands:

    c4 make                  # build and install of nvidia driver user libraries
    c4 make build            # build of nvidia driver user libraries
    c4 make install          # install of nvidia driver user libraries
    c4 make clean            # remove all artifacts

    c4 make test             # Run tests - CURRENTLY UNUSED

EOF
}

FLAVOR=standard-EXASOL-7.0.0
EXASLCT_TMP="$HOME/exaslct-tmp"
EXASLCT_BASE_TMP="$EXASLCT_TMP/tmp"
EXASLCT_BUILD_OUTPUT="$EXASLCT_TMP/.build_output"
EXPORT_PATH="$BUILDSYSTEM_LINKDIR"

get_image_hash()
{
  cat "$BUILDSYSTEM_LINKDIR/install/build_info/image_info/$FLAVOR-release" \
  | jq -r .hash | cut -c 1-8
}

## CMD Functions: General C4 Query Commands - Not explicitly used by the user 
_cmd_prefix() {
    prepare_variables
    HASH=$(get_image_hash)
    HASH=${HASH:-NOHASH}

    PREFIX=/usr/opt/${EXASUITE}/ScriptLanguages-${FLAVOR}-${HASH}
    echo "$PREFIX"
    exit "$?"
}

_cmd_provides() {
  echo script-language-${FLAVOR}
}

_cmd_requires() {
  echo
}

prepare_variables() {
  # TODO: TOOLCHAIN will be provided in CURRENTTOOLCHAIN and EXARUNTIME will be provided in CCC_BUILDENV_TOOLCHAIN when branch ic.config got merged
  EXASUITE=EXASuite-7
  EXARUNTIME=$(cat ./config/build-env | sed -E "s/ +/ /g" | grep "exaruntime = " | cut -f 3 -d " ")  
  EXARUNTIME_PATH="$EXARUNTIME"
  TOOLCHAIN="/usr/opt/${EXASUITE}/${EXARUNTIME_PATH}"
  export PATH="$TOOLCHAIN/bin:$PATH"
}

prepare_exaslct() {
  c4 initialize wait docker
  prepare_variables
  mkdir -p "$EXASLCT_BASE_TMP"
  mkdir -p "$EXASLCT_BUILD_OUTPUT"
  "$CCC_CCC" extract -m "@${EXARUNTIME}"
  EXASLCT_OPTIONS=(--temporary-base-directory "$EXASLCT_BASE_TMP" --output-directory "$EXASLCT_BUILD_OUTPUT")
}

_cmd_build_container() {
  echo _cmd_build_container
  if [[ "$BUILDSYSTEM_ALIAS" =~ .*\.params.*\.-flavor=\'([^\']+)\'.* ]]
  then
    echo found flacor
    echo "$BUILDSYSTEM_ALIAS" | sed -E "s/.*\.params.*\.-flavor='([^']+)'.*/\1/g"
  fi
#  prepare_exaslct
#  PIP_INSTALL=YES ./exaslct export --flavor-path="flavors/${FLAVOR}" --export-path "$EXPORT_PATH" "${EXASLCT_OPTIONS[@]}" \
#  && mkdir -p "$INSTALL_PATH" \
#  && for f in "$EXPORT_PATH/"*.gz; do echo "Extracting $f" ;tar xfC "$f" "$INSTALL_PATH"; done
}

_cmd_build_src_package() {
  echo "build_src_package"
}

_cmd_build() {
  mkdir -p "$BUILDSYSTEM_LINKDIR"
  INSTALL_PATH="$BUILDSYSTEM_LINKDIR/install"
  git submodule update
  echo BUILDSYSTEM_ALIAS "$BUILDSYSTEM_ALIAS"
  if [[ "$BUILDSYSTEM_ALIAS" =~ .*\.params.*\.-package=\'src\'.* ]]
  then
    _cmd_build_src_package
  elif [[ "$BUILDSYSTEM_ALIAS" =~ .*\.params.*\.-package=\'container\'.* ]]
  then
    echo params _cmd_build_container
    _cmd_build_container
  else
    echo default _cmd_build_container
    _cmd_build_container
  fi
}

_cmd_clean() {
  prepare_exaslct
  echo "Cleaning"
  PIP_INSTALL=YES ./exaslct clean-flavor-images --flavor-path "flavors/${FLAVOR}" "${EXASLCT_OPTIONS[@]}"
  rm -rf "$EXASLCT_TMP"
  rm -rf "$INSTALL_PATH"
  rm -rf "$EXPORT_PATH/"*.gz
  rm -rf "$BUILDSYSTEM_LINKDIR"
}

_cmd_test() {
  prepare_exaslct
  PIP_INSTALL=YES ./exaslct run-db-test --flavor-path "flavors/${FLAVOR}" "${EXASLCT_OPTIONS[@]}"
}


## Command Switch
if [ "$1" = prefix ]; then
  _cmd_prefix
elif [ "$1" = make ]; then
  {
    _cmd_build
  } > build.log
elif [ "$1" = "clean" ]; then
  _cmd_clean
elif [ "$1" = provides ]; then
  _cmd_provides
elif [ "$1" = requires ]; then
  _cmd_requires
elif [ "$1" = test ]; then
  shift
  _cmd_test "$@"
elif [ "$1" = help-more ]; then # help is already in use by main c4 path
  _cmd_help
else
  _cmd_help
fi
