name: Build with c4

on:
  push:
    branches:
      - "*"
jobs:
  build:
    environment: c4_ci
    env:
      CCC_AWS_KEY_PAIR_FILE_RELATIVE: .ssh/id_rsa
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install
        aws --version
    - name: Create AWS Config
      run: |
        mkdir $HOME/.aws/
        bash .github/workflows/create_aws_config.sh $HOME/.aws/
      env:
        AWS_GET_ROLE: ${{ secrets.AWS_GET_ROLE }}
    - name: Get c4 release
      run: |
        aws s3 --profile default-mfa --region eu-west-1 cp s3://x-u/tag/ccc-release .
        aws s3 --profile default-mfa --region eu-west-1 cp s3://x-u/$(cat ccc-release | sed s@-@/@).tar.gz ccc.tar.gz
        tar xf ccc.tar.gz ./bin/c4.static
        chmod +x ./bin/c4.static

    - name: Greate SSH Private Key
      run: |
        mkdir $HOME/.ssh/
        CCC_AWS_KEY_PAIR_FILE=$HOME/$CCC_AWS_KEY_PAIR_FILE_RELATIVE
        bash .github/workflows/create_ssh_key.sh $CCC_AWS_KEY_PAIR_FILE
      env:
        SSH_KEY_PEM: ${{ secrets.SSH_KEY_PEM }}
    - name: Create c4 config
      run: |
        mkdir $HOME/.ccc/
        export CCC_AWS_KEY_PAIR_FILE=$HOME/$CCC_AWS_KEY_PAIR_FILE_RELATIVE
        bash .github/workflows/create_c4_config.sh $HOME/.ccc/
      env:
        CCC_USER_BLAU_USER: ${{ secrets.CCC_USER_BLAU_USER }}
        CCC_USER_EMAIL: ${{ secrets.CCC_USER_EMAIL }}
        CCC_USER_FULLNAME: ${{ secrets.CCC_USER_FULLNAME }}
        CCC_USER_GITHUB_USER: ${{ secrets.CCC_USER_GITHUB_USER }}
        CCC_USER_USERNAME: ${{ secrets.CCC_USER_USERNAME }}
        SSH_KEY_NAME: ${{ secrets.SSH_KEY_NAME }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Create c4 play
      run: |
        ./bin/c4.static aws diag
        #set -x
        #./bin/c4.static aws new --ccc-play-off true --make true --upload true -AC git.script-languages-release  2>&1 | tee c4_new.log
        #sleep 120
        #ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $(cat c4_new.log | grep "ubuntu@ec2") tail -n 10000000 -f */c4-make.log
