name: Check for rebuild

on:
  push:
    branches-ignore:
      - "master"
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Check if the branch triggers a rebuild
      run: "bash .github/workflows/check_for_rebuild_branch.sh"
