name: Check error codes

on:
  push:
    branches:
      - master
      - develop
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Search for duplicated error codes
      run: bash find_duplicate_error_codes.sh

