name: Check package diff tool

on:
  pull_request:
    branches:
      - develop

jobs:
  check_package_diff:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0
        submodules: 'recursive'

    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@v5
      with:
        python-version: "3.10"
        poetry-version: "2.3.0"

    - name: Setup Poetry
      run: |
        PYTHON_BIN=$(command -v "python3.10")
        poetry env use "$PYTHON_BIN"
        poetry install
        poetry_env_path=$(poetry env info --path)
        echo "poetry_env_path=$poetry_env_path" >> $GITHUB_ENV

    - name: Run exaslct generate-package-diffs
      run: |
        source "${{ env.poetry_env_path }}/bin/activate"
        SLC_VERSION=$(poetry version --short)
        poetry run exaslct generate-package-diffs --output-package-diff-directory doc/changes/package_diffs/${SLC_VERSION}/ --current-working-copy-name ${SLC_VERSION}

    - name: Check if package diff have changed
      run: |
        [ -z "$(git status --porcelain=v1 -uno 2>/dev/null)" ]
