name: Check Rollback Script 7.1.30

on:
  push:
    branches:
      - develop
  pull_request:


jobs:
  Check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Setup Python & Poetry Environment
        uses: exasol/python-toolbox/.github/actions/python-environment@0.12.0
        with:
          python-version: "3.10"
          poetry-version: '1.8.2'
      - name: Start ITDE
        run: poetry run itde spawn-test-environment --environment-name exasol_test --database-port-forward 8888 --bucketfs-port-forward 6583 --docker-db-image-version=7.1.29;
      - name: Run Skript
        run: bash install_slc_v6.0.0_on_db.sh localhost 6583 write bfsdefault default HTTP
        working-directory: doc/user_guide/resources