name: Check PullRequest

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Check if the branch triggers a rebuild
      run: "bash .github/workflows/check_pull_request.sh ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.base.ref }}"
