name: Check Markdown links

on:
  push:
    branches:
      - master
      - develop
  pull_request:


jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Init submodules
        run: git submodule update --init --recursive
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          config-file: '.github/markdown_check_config.json'