#!/bin/bash

set -euo pipefail

(

FILE_PREFIX="$1"

CONFIG_FILE="$FILE_PREFIX/config"

touch "$CONFIG_FILE"
echo "CCC_USER_USERNAME=$CCC_USER_USERNAME" >> "$CONFIG_FILE"
echo "CCC_USER_FULLNAME=$CCC_USER_FULLNAME" >> "$CONFIG_FILE"
echo "CCC_USER_GITHUB_USER=$CCC_USER_GITHUB_USER" >> "$CONFIG_FILE"
echo "CCC_USER_EMAIL=$CCC_USER_EMAIL" >> "$CONFIG_FILE"
echo "CCC_AWS_KEY_PAIR=$CCC_AWS_KEY_PAIR" >> "$CONFIG_FILE"
echo "CCC_USER_BLAU_USER=$CCC_USER_BLAU_USER" >> "$CONFIG_FILE"
echo "CCC_AWS_KEY_PAIR_FILE=$CCC_AWS_KEY_PAIR_FILE" >> "$CONFIG_FILE"
echo "CCC_USER_GITHUB_TOKEN=$GITHUB_TOKEN" >> "$CONFIG_FILE"

)# &> /dev/null
