#!/bin/bash

set -euo pipefail

(

FILE_PREFIX="$1"

CONFIG_FILE="$FILE_PREFIX/config"

touch "$CONFIG_FILE"
echo "CCC_USER_USERNAME=$CCC_USER_USERNAME"
echo "CCC_USER_FULLNAME=$CCC_USER_FULLNAME"
echo "CCC_USER_GITHUB_USER=$CCC_USER_GITHUB_USER"
echo "CCC_USER_EMAIL=$CCC_USER_EMAIL"
echo "CCC_AWS_KEY_PAIR=$CCC_AWS_KEY_PAIR"
echo "CCC_USER_BLAU_USER=$CCC_USER_BLAU_USER"
echo "CCC_AWS_KEY_PAIR_FILE=$CCC_AWS_KEY_PAIR_FILE"
echo "CCC_USER_GITHUB_TOKEN=$GITHUB_TOKEN"

) &> /dev/null
