name: Nightly

on:
  push:
    branches-ignore:
      - "master"
  # schedule:
  #   # * is a special character in YAML so you have to quote this string
  #   - cron:  '0 1 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.0
      with:
        timeZone: 0
        format: 'YYYY_MM_DD_HH_mm_ss'

    - name: Create new empty commit 
      run: |
        git checkout -b rebuild/nightly_${{ steps.time.outputs.time }}
        git config --local user.email "opensource@exasol.com"
        git config --local user.name "GitHub Action"
        git commit --allow-empty -m 'nightly_${{ steps.time.outputs.time }}'

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: rebuild/nightly_${{ steps.time.outputs.time }}
