name: Release Droid - Upload GitHub Release Assets

on:
  workflow_dispatch:
    inputs:
      upload_url:
        description: 'Upload URL'
        required: true

jobs:

  build_and_upload:
    environment: AWS
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Init submodules
      run: git submodule update --init --recursive

    - name: Setup Python & Poetry Environment
      uses: exasol/python-toolbox/.github/actions/python-environment@0.12.0
      with:
        python-version: "3.10"
        poetry-version: '1.8.2'

    - name: Start release
      run: poetry run python -m exasol_script_languages_container_ci_setup.main start-release-build --log-level info --project "ScriptLanguagesRelease" --upload-url "${{ github.event.inputs.upload_url }}" --branch "$GITHUB_REF"
      env: # Set the secret as an env variable
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
        GITHUB_TOKEN: ${{ github.token }}
