name: Validate PR

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:

      - name: Check master
        if: ${{github.base_ref == 'master' && github.base_ref != 'develop'}}
        run: echo You must not merge to master && exit 1
