name: Validate PR

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-24.04
    steps:
      - name: Check master
        if: ${{github.base_ref == 'master' && github.ref_name != 'develop'}}
        run: echo You must not merge directly to master. Instead merge to 'develop' first. && exit 1
